name: Generate terraform docs
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  terraform-docs:
    name: Generate Terraform docs
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'terraform-docs') }}
    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v3
    - name: Render terraform docs for aws-multi-region and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: aws-multi-region
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for aws-single-region and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: aws-single-region
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for azure-single-region and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: azure-single-region
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for gke-cluster and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: gke-cluster
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for aws-yba-universe and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: aws-yba-universe
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for gke-multi-region and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: gke-multi-region
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for aks-cluster and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: aks-cluster
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
    - name: Render terraform docs for azure-infrastructure-only and push changes back
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: azure-infrastructure-only
        output-file: "README.md"
        output-format: "markdown table"
        output-method: "inject"
        git-push: "true"
